CREATE TABLE student (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    roll_no VARCHAR(50) NOT NULL UNIQUE,
    room_no VARCHAR(20),
    phone VARCHAR(20),
    email VARCHAR(100),
    hostel_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE
);